
package webservices;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WebServices", targetNamespace = "http://webservices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    webservices.ObjectFactory.class,
    net.java.dev.jaxb.array.ObjectFactory.class
})
public interface WebServices {


    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarDepartamentosRequest", output = "http://webservices/WebServices/listarDepartamentosResponse")
    public StringArray listarDepartamentos();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getInfoBasicaUsuarioRequest", output = "http://webservices/WebServices/getInfoBasicaUsuarioResponse")
    public DtUsuario getInfoBasicaUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtSalidaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarInfoSalidasTuristaRequest", output = "http://webservices/WebServices/listarInfoSalidasTuristaResponse")
    public DtSalidaArray listarInfoSalidasTurista(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @throws InscriptionFailException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/WebServices/ingresarInscripcionRequest", output = "http://webservices/WebServices/ingresarInscripcionResponse", fault = {
        @FaultAction(className = InscriptionFailException_Exception.class, value = "http://webservices/WebServices/ingresarInscripcion/Fault/InscriptionFailException")
    })
    public void ingresarInscripcion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2,
        @WebParam(name = "arg3", partName = "arg3")
        XMLGregorianCalendar arg3,
        @WebParam(name = "arg4", partName = "arg4")
        TipoInscripcion arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5)
        throws InscriptionFailException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarActividadesDepartamentoRequest", output = "http://webservices/WebServices/listarActividadesDepartamentoResponse")
    public StringArray listarActividadesDepartamento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns webservices.DtSalidaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarInfoSalidasVigentesRequest", output = "http://webservices/WebServices/listarInfoSalidasVigentesResponse")
    public DtSalidaArray listarInfoSalidasVigentes(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        XMLGregorianCalendar arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg10
     * @param arg11
     * @param arg12
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @throws YaExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/WebServices/altaActividadTuristicaRequest", output = "http://webservices/WebServices/altaActividadTuristicaResponse", fault = {
        @FaultAction(className = YaExisteException_Exception.class, value = "http://webservices/WebServices/altaActividadTuristica/Fault/YaExisteException")
    })
    public void altaActividadTuristica(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3,
        @WebParam(name = "arg4", partName = "arg4")
        float arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        XMLGregorianCalendar arg7,
        @WebParam(name = "arg8", partName = "arg8")
        byte[] arg8,
        @WebParam(name = "arg9", partName = "arg9")
        String arg9,
        @WebParam(name = "arg10", partName = "arg10")
        String arg10,
        @WebParam(name = "arg11", partName = "arg11")
        String arg11,
        @WebParam(name = "arg12", partName = "arg12")
        EstadoActividad arg12)
        throws YaExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     */
    @WebMethod
    @Action(input = "http://webservices/WebServices/actualizarUsuarioRequest", output = "http://webservices/WebServices/actualizarUsuarioResponse")
    public void actualizarUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        XMLGregorianCalendar arg3,
        @WebParam(name = "arg4", partName = "arg4")
        byte[] arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        String arg9);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg10
     * @param arg11
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/WebServices/altaUsuarioRequest", output = "http://webservices/WebServices/altaUsuarioResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webservices/WebServices/altaUsuario/Fault/Exception")
    })
    public void altaUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        byte[] arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        String arg9,
        @WebParam(name = "arg10", partName = "arg10")
        String arg10,
        @WebParam(name = "arg11", partName = "arg11")
        String arg11)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarUsuariosRequest", output = "http://webservices/WebServices/listarUsuariosResponse")
    public StringArray listarUsuarios();

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarCategoriasRequest", output = "http://webservices/WebServices/listarCategoriasResponse")
    public StringArray listarCategorias();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtActividad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getInfoActividadRequest", output = "http://webservices/WebServices/getInfoActividadResponse")
    public DtActividad getInfoActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtActividadArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarActividadesFinalizablesProveedorRequest", output = "http://webservices/WebServices/listarActividadesFinalizablesProveedorResponse")
    public DtActividadArray listarActividadesFinalizablesProveedor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.InscripcionDaoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarSalidasDeActividadesFinalizadasPorTuristaRequest", output = "http://webservices/WebServices/listarSalidasDeActividadesFinalizadasPorTuristaResponse")
    public InscripcionDaoArray listarSalidasDeActividadesFinalizadasPorTurista(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtActividadArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarInfoCompletaActividadesProveedorRequest", output = "http://webservices/WebServices/listarInfoCompletaActividadesProveedorResponse")
    public DtActividadArray listarInfoCompletaActividadesProveedor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtActividadArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarActividadesConfirmadasProveedorRequest", output = "http://webservices/WebServices/listarActividadesConfirmadasProveedorResponse")
    public DtActividadArray listarActividadesConfirmadasProveedor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.ActividadDaoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarActividadesFinalizadasProveedorRequest", output = "http://webservices/WebServices/listarActividadesFinalizadasProveedorResponse")
    public ActividadDaoArray listarActividadesFinalizadasProveedor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarPaquetesRequest", output = "http://webservices/WebServices/listarPaquetesResponse")
    public StringArray listarPaquetes();

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarActividadesConfirmadasRequest", output = "http://webservices/WebServices/listarActividadesConfirmadasResponse")
    public StringArray listarActividadesConfirmadas();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @throws YaExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/WebServices/altaSalidaTuristicaRequest", output = "http://webservices/WebServices/altaSalidaTuristicaResponse", fault = {
        @FaultAction(className = YaExisteException_Exception.class, value = "http://webservices/WebServices/altaSalidaTuristica/Fault/YaExisteException")
    })
    public void altaSalidaTuristica(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3,
        @WebParam(name = "arg4", partName = "arg4")
        XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        byte[] arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7)
        throws YaExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtSalida
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getInfoCompletaSalidaRequest", output = "http://webservices/WebServices/getInfoCompletaSalidaResponse")
    public DtSalida getInfoCompletaSalida(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getUsuarioByNickNameRequest", output = "http://webservices/WebServices/getUsuarioByNickNameResponse")
    public DtUsuario getUsuarioByNickName(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/verifiedUserPasswordRequest", output = "http://webservices/WebServices/verifiedUserPasswordResponse")
    public boolean verifiedUserPassword(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarPaquetesCategoriaRequest", output = "http://webservices/WebServices/listarPaquetesCategoriaResponse")
    public StringArray listarPaquetesCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/existeUsuarioConEmailRequest", output = "http://webservices/WebServices/existeUsuarioConEmailResponse")
    public boolean existeUsuarioConEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/existeUsuarioConNicknameRequest", output = "http://webservices/WebServices/existeUsuarioConNicknameResponse")
    public boolean existeUsuarioConNickname(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtPaqueteArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/busquedaTextoPaquetesRequest", output = "http://webservices/WebServices/busquedaTextoPaquetesResponse")
    public DtPaqueteArray busquedaTextoPaquetes(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.SalidaDaoArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarSalidasFinalizadasRequest", output = "http://webservices/WebServices/listarSalidasFinalizadasResponse")
    public SalidaDaoArray listarSalidasFinalizadas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtActividadArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/busquedaTextoActividadesRequest", output = "http://webservices/WebServices/busquedaTextoActividadesResponse")
    public DtActividadArray busquedaTextoActividades(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtProveedor
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getProveedorByNicknameRequest", output = "http://webservices/WebServices/getProveedorByNicknameResponse")
    public DtProveedor getProveedorByNickname(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.SalidaDao
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getSalidaDeActividadFinalizadaRequest", output = "http://webservices/WebServices/getSalidaDeActividadFinalizadaResponse")
    public SalidaDao getSalidaDeActividadFinalizada(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.ActividadDao
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getActividadFinalizadaRequest", output = "http://webservices/WebServices/getActividadFinalizadaResponse")
    public ActividadDao getActividadFinalizada(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtTurista
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getInfoTuristaRequest", output = "http://webservices/WebServices/getInfoTuristaResponse")
    public DtTurista getInfoTurista(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns byte[]
     * @throws DocumentException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getFilePdfRequest", output = "http://webservices/WebServices/getFilePdfResponse", fault = {
        @FaultAction(className = DocumentException_Exception.class, value = "http://webservices/WebServices/getFilePdf/Fault/DocumentException"),
        @FaultAction(className = IOException_Exception.class, value = "http://webservices/WebServices/getFilePdf/Fault/IOException")
    })
    public byte[] getFilePdf(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws DocumentException_Exception, IOException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/existeUsuarioEmailRequest", output = "http://webservices/WebServices/existeUsuarioEmailResponse")
    public boolean existeUsuarioEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/existeUsuarioNickRequest", output = "http://webservices/WebServices/existeUsuarioNickResponse")
    public boolean existeUsuarioNick(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getUsuarioByEmailRequest", output = "http://webservices/WebServices/getUsuarioByEmailResponse")
    public DtUsuario getUsuarioByEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getFileImgRequest", output = "http://webservices/WebServices/getFileImgResponse")
    public byte[] getFileImg(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @throws CompraFailException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/WebServices/ingresarCompraRequest", output = "http://webservices/WebServices/ingresarCompraResponse", fault = {
        @FaultAction(className = CompraFailException_Exception.class, value = "http://webservices/WebServices/ingresarCompra/Fault/CompraFailException")
    })
    public void ingresarCompra(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2,
        @WebParam(name = "arg3", partName = "arg3")
        XMLGregorianCalendar arg3)
        throws CompraFailException_Exception
    ;

    /**
     * 
     * @return
     *     returns webservices.DtTurista
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getDTTuristaRequest", output = "http://webservices/WebServices/getDTTuristaResponse")
    public DtTurista getDTTurista();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtPaquete
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getInfoPaqueteRequest", output = "http://webservices/WebServices/getInfoPaqueteResponse")
    public DtPaquete getInfoPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://webservices/WebServices/followUnfollowRequest", output = "http://webservices/WebServices/followUnfollowResponse")
    public void followUnfollow(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://webservices/WebServices/agregarVisitaRequest", output = "http://webservices/WebServices/agregarVisitaResponse")
    public void agregarVisita(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        boolean arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtInscripcionArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getInscripcionesRequest", output = "http://webservices/WebServices/getInscripcionesResponse")
    public DtInscripcionArray getInscripciones(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://webservices/WebServices/marcarDesmarcarFavRequest", output = "http://webservices/WebServices/marcarDesmarcarFavResponse")
    public void marcarDesmarcarFav(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://webservices/WebServices/finalizarActividadRequest", output = "http://webservices/WebServices/finalizarActividadResponse")
    public void finalizarActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
