
package webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "InscriptionFailException", targetNamespace = "http://webservices/")
public class InscriptionFailException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InscriptionFailException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InscriptionFailException_Exception(String message, InscriptionFailException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public InscriptionFailException_Exception(String message, InscriptionFailException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.InscriptionFailException
     */
    public InscriptionFailException getFaultInfo() {
        return faultInfo;
    }

}
