
package webservices;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WebServices", targetNamespace = "http://webservices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    net.java.dev.jaxb.array.ObjectFactory.class,
    webservices.ObjectFactory.class
})
public interface WebServices {


    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarDepartamentosRequest", output = "http://webservices/WebServices/listarDepartamentosResponse")
    public StringArray listarDepartamentos();

    /**
     * 
     * @param arg0
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarActividadesDepartamentoRequest", output = "http://webservices/WebServices/listarActividadesDepartamentoResponse")
    public StringArray listarActividadesDepartamento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarCategoriasRequest", output = "http://webservices/WebServices/listarCategoriasResponse")
    public StringArray listarCategorias();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtActividad
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getInfoActividadRequest", output = "http://webservices/WebServices/getInfoActividadResponse")
    public DtActividad getInfoActividad(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarPaquetesRequest", output = "http://webservices/WebServices/listarPaquetesResponse")
    public StringArray listarPaquetes();

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtSalida
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getInfoCompletaSalidaRequest", output = "http://webservices/WebServices/getInfoCompletaSalidaResponse")
    public DtSalida getInfoCompletaSalida(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @throws YaExisteException_Exception
     */
    @WebMethod
    @Action(input = "http://webservices/WebServices/altaSalidaTuristicaRequest", output = "http://webservices/WebServices/altaSalidaTuristicaResponse", fault = {
        @FaultAction(className = YaExisteException_Exception.class, value = "http://webservices/WebServices/altaSalidaTuristica/Fault/YaExisteException")
    })
    public void altaSalidaTuristica(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3,
        @WebParam(name = "arg4", partName = "arg4")
        XMLGregorianCalendar arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6)
        throws YaExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/listarPaquetesCategoriaRequest", output = "http://webservices/WebServices/listarPaquetesCategoriaResponse")
    public StringArray listarPaquetesCategoria(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservices.DtPaquete
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/WebServices/getInfoPaqueteRequest", output = "http://webservices/WebServices/getInfoPaqueteResponse")
    public DtPaquete getInfoPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
