
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WebServicesService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:9128/webservices?wsdl")
public class WebServicesService
    extends Service
{

    private final static URL WEBSERVICESSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICESSERVICE_EXCEPTION;
    private final static QName WEBSERVICESSERVICE_QNAME = new QName("http://webservices/", "WebServicesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9128/webservices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICESSERVICE_WSDL_LOCATION = url;
        WEBSERVICESSERVICE_EXCEPTION = e;
    }

    public WebServicesService() {
        super(__getWsdlLocation(), WEBSERVICESSERVICE_QNAME);
    }

    public WebServicesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICESSERVICE_QNAME, features);
    }

    public WebServicesService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICESSERVICE_QNAME);
    }

    public WebServicesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICESSERVICE_QNAME, features);
    }

    public WebServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServices
     */
    @WebEndpoint(name = "WebServicesPort")
    public WebServices getWebServicesPort() {
        return super.getPort(new QName("http://webservices/", "WebServicesPort"), WebServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServices
     */
    @WebEndpoint(name = "WebServicesPort")
    public WebServices getWebServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "WebServicesPort"), WebServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICESSERVICE_EXCEPTION!= null) {
            throw WEBSERVICESSERVICE_EXCEPTION;
        }
        return WEBSERVICESSERVICE_WSDL_LOCATION;
    }

}
