
package webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "YaExisteException", targetNamespace = "http://webservices/")
public class YaExisteException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private YaExisteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public YaExisteException_Exception(String message, YaExisteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public YaExisteException_Exception(String message, YaExisteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.YaExisteException
     */
    public YaExisteException getFaultInfo() {
        return faultInfo;
    }

}
